### ISSUE TITLE
c++ main file not working 

### ISSUE THREAD

**Issue by SUSHANTH009** [suleymanozkeskin/btc_aggregated_orderbook#3]
<img width="1056" alt="Screenshot 2024-03-24 at 1 50 05 AM" src="https://github.com/suleymanozkeskin/btc_aggregated_orderbook/assets/90193727/7c63752c-1316-4df8-b936-5df88858c0ad">

**Comment by suleymanozkeskin** [comment]
This is fixed now, please follow the instructions [here](https://github.com/suleymanozkeskin/btc_aggregated_orderbook/blob/master/README.md)

**Comment by suleymanozkeskin** [comment]
This is fixed now, please follow the instructions [here](https://github.com/suleymanozkeskin/btc_aggregated_orderbook/blob/master/README.md)
